import fs from 'fs';
import path from 'path';

const outDir = 'public/icons';
const inDir = 'output_vectors';

function fix() {
    const files = fs.readdirSync(inDir).filter(f => f.endsWith('.svg'));
    // wait, I also need to process the NON-output_vectors files! 
    // They were correctly generated by generate_portfolio_icons.js though!
}
